
spring:
  application:
    name: discovery
 
#Tomcat Embedded Server Configuration
server: 
  port: 8888
 
#Eureka Configuration Properties
eureka:
  instance:
    hostname: localhost
  client:
    serviceURL:
      defaultZone: http://localhost:8888/eureka/
    registerWithEureka: false
    fetchRegistry: false